replicaCount: 4

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: 
  limits:
    cpu: "400m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"