replicaCount: 4

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: "400m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}