replicaCount: 2

image:
  repository: [[ .Values.image.repository ]]
  tag: [[ .Values.image.tag ]]
  pullPolicy: IfNotPresent

service:
  type: [[ .Values.service.type ]]
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: {{ .Values.resources.limits.cpu | quote}}
    memory: {{ .Values.resources.limits.memory | quote}}
  requests:
    cpu: {{ .Values.requests.cpu | quote}}
    memory: {{ .Values.requests.memory | quote}}

nodeSelector: {}

tolerations: []

affinity: {}