replicaCount: 3
image:
  repository: custom-nginx
  tag: 1.20.0
service:
  type: NodePort
  port: 8080
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"