apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZivISM/argocd-helm-drills.git
    targetRevision: main 
    path: drill1/charts/myapp
    helm:
      valueFiles:
        - custome-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true